language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js:
  - "6"
  - "8"
  - "node"

script:
  - npm run eslint
  - npm run test-cov

after_script:
  - npm install coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

dist: trusty
