language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js:
  - "0.12"
  - "4"
  - "6"

script:
  - npm run eslint
  - npm run jscs
  - npm run test-cov

after_script:
  - npm install coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
