language: node_js

addons:
  apt:
    packages:
    - time

cache:
  npm: true

node_js:
  - "8"
  - "10"
  - "12"
  - "13"

script:
  - npm run eslint
  - npm run test-cov
  - npm install 0x -g
  - ./test/benchmark.sh

after_script:
  - npm install coveralls
  - nyc report --reporter=text-lcov | coveralls
