os: linux

language: node_js

cache:
  npm: true

node_js:
  - "10"
  - "12"
  - "14"

script:
  - node ./test/benchmark.js --only-profiling

deploy:
  provider: surge
  project: ./0x/
  skip_cleanup: true
  domain: "${TRAVIS_COMMIT}-${TRAVIS_NODE_VERSION}-hexo.surge.sh"
  on:
    all_branches: true
